### ISSUE TITLE
/now Pages

### ISSUE THREAD

**Issue by necopinus** [vgururao/yakcollective#47]
See: https://nownownow.com/about

Two place for this:

- https&zwnj;://www.yakcollective.org/members/**member-page**/now (member-specific now)
- https&zwnj;://www.yakcollective.org/now (projects, etc. in progress, maybe also aggregate member /now pages)

Idea via Jenna Dixon on the 2020-07-18 #infrastructure chat.

Probably makes the most sense in the context of modular content (#46), and thus depends on migrating to Gatsby (#12).

**Comment by tilnow** [comment]
suggestion: many yaks have their own websites with their own /now pages (or not). is our goal to force them to make this website part of their routine (we do not want stale now pages) or perhaps to latch onto existing now data (e.g., extract hashtags from tweets, etc.)

**Comment by necopinus** [comment]
It would be great to just pull in the content of existing `/now` pages. The problem is that I think we need a feed of some kind to do this, and most folks aren't providing a nice feed (this is why not everyone's blog posts/newsletters are pulling into `/writings`).

I wish people were more religious about using RSS.

**Comment by tilnow** [comment]
i think by nature now pages are not so organized. why doesn't it make more sense to just list the links in the combined now page?
in the personal now page (per member), maybe non-uniform format does not matter so much.

can you give me links to 3-4 now pages you feel are problematic? diverse?

**Comment by necopinus** [comment]
It's not that I'm thinking that the pages need to be structured, but rather that I'm thinking, "how do we get the content?" There's two general approaches to this:

1. Members write their own pages for the site. I don't think this is a good option, both because it's duplicative of content that already exists (for members with `/now` pages or well-structured blogs/sites), or because people just won't do it (the YC.org website's probably always going to have a bit higher of a barrier to contributing than platform X).

2. We pull in the content from somewhere else. This means scraping sites (never ends well) or tapping into some kind of feed that can just hand us the content. I'd rather do the latter. I honestly don't care to be prescriptive about how it's structured... We just kind of need a blob of HTML in this case. Once we have that blob, it can be turned into `/now` pages on YC.org, embedded in a "central" `/now` page, whatever.

I _think_ the 3rd alternative being proposed here is basically just to make the `/now` pages on YC.org redirects to actual member `/now` pages. We could definitely do this (it wouldn't be much harder than adding a field to the member files in `_members`), but if possible I think it's still worth caching content on the back end, like we do with blog posts. That opens up a lot of avenues for potential future remixing/use (for example, we could have a feed of `/now` pages, just like we have a feed of member posts).

If we go with plain redirects, I think the way to do this would be:

1. Go through the YC member files and add a field for `/now` pages, when they exist. We might want to think about whether we want to expose this elsewhere too.
2. Move back to using a [`_redirects` file for redirects](https://docs.netlify.com/routing/redirects/), rather than using `netlify.toml`.
3. Turn `_redirects` into a file that's processed by Jekyll (later: Gatsby) and pulls in the relevant URLs from the `members` collection.

I have this hazy notion that there's a `.well-known` proposal for `/now` pages, or something similar?

**Comment by necopinus** [comment]
Setting this to the new v2.5 milestone for now, but might bump to v3.0+.

**Comment by tilnow** [comment]
well i recall seeing a proposal for now pages. i think we need to build a protocol(?) for yak->member transfer. that will include asking the yak if he has a now page (and then we can even simply iframe it) or build his own on yak-collective if he does not (and then also iframe it).
to be honest, i do not see why we mind if to see a member's now page, a browser leaves the-yak-collective? he can always do "back" and the goal _is_ to get website viewers to go to member pages, no? if you agree, would just add a link to the now page. could be "open in a new tab" if you want.
if you ever want the content of now pages (what does caching mean when it is dynamically changing), we can just scrape it at that time. i would not want such a cache if i could not enforce something about format. which i can at yc. in fact, maybe some members will simply use the now page at yc, rather than modify their website.

**Comment by tilnow** [comment]
i think you meant [this page](https://sivers.org/now3)

**Comment by necopinus** [comment]
I'm not trying to force folks to stay on YC.org. I'm thinking about caching in a way that's analogous to how we handle writings (which we use for record-keeping, but don't actually expose directly).

In any event, it's worth pinging existing folks on Discord. The way I found most of the feeds was just by manually crawling people's websites (which I scrapped off of the project decks), locating the feed, and then DM'ing them on Discord for a negative check-off ("planning to use this feed for purpose X, any objections?")

As far as a `.well-known` proposal goes, I was referring to the [IANA `.well-known` URIs](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml). I think I was confusing the `/now` proposal you link to (which doesn't propose a `.well-known URI) with the [`security.txt`](https://securitytxt.org/) proposal (which does propose a `.well-known` URI).

**Comment by vgururao** [comment]
I'm not sure I totally get the point of this. The member page is effectively a restricted now page for the subset of activities related to YC, and for other stuff they can click through to the member's various web presence links. If the intent is to present a richer view of ALL of a member's activities, I'm not sure how you would even get that data. I run like 5 websites and have a poorly updated central page at venkateshrao.com that's usually months out of date. I don't follow the convention of a now page, so the only way to construct one for me automatically would beuto poll all my websites somehow. Perhaps what we need is a narrower and closed definition of "now" that can be a box rather than a page on the member page, with specific fields we want to try and keep populated in an up-to-date way? Otherwise this feels like a boil-the-ocean AI-complete feature. I think I could barely construct a /now state page for myself, let alone automate it for an arbitrary group of people with idiosyncratic web presences.

**Comment by tilnow** [comment]
so, let me go with that and rephrase the question. what *now* information do you think is relevant for both yaks and YC.org? is the now stuff what matters or rather skills?

i also assume that it makes sense if YC maintain now pages, etc. for members who do not have such  web page, as an opt in.

**Comment by vgururao** [comment]
Current employment situation/position/location/availability for gigs/skills/recent writings/currently-reading (books)

Now is naturally the dual of best-of-all-time. The closest to a now page I have is a now-reading page

**Comment by tilnow** [comment]
except for now reading, that seems like what the current design is/was meant to include. do you think it makes sense to ask the yak, periodically, about any of the information, like about availability for new gigs?

**Comment by vgururao** [comment]
I thought idea was to let members eventually edit these themselves

**Comment by tilnow** [comment]
as a general statement, yes. but if we want yaks to update frequently, we should be reminding them and also take away as much of the overhead as possible. 

so, ask something like:  yak if to update availability to a number 1-5 and give him option to also click on “manual edit” and make more detailed changes. 

now, the goal is, i think, how to make this a useful part of the yak’s workflow, rather than an added task. not sure how yet.

**Comment by necopinus** [comment]
I'm bumping this to a later milestone. The idea is less well defined than I'd hoped based on this discussion, as is what we want the Yak-side UX to be.

Let's keep thinking about this though... I'm not sure it's a _bad_ idea. Just not as fully formed as we need right now.

**Comment by necopinus** [comment]
Change of focus, per today's infrastructure chat: Make this a broad "what the YC is working on right now. Drop member `/now` pages entirely (at least for the time being).

Medium-term, some (all?) stats on this page should get pulled from Knack, once project tracking lives there. Maybe Roam, if/when they ever get an API.

**Comment by necopinus** [comment]
Closed by f73bfda.
